Add structure
magieno/pristine-starter pull request #1
Opened 2021-10-26 17:13 UTC by mathieugh

2021-10-26 18:25 UTC, etiennenoel requested changes

2021-10-26 18:25 UTC, etiennenoel commented on package.json
> +    "express": " REGION=us-east-1 NAMESPACE=app.ca ts-node --project tsconfig.cjs.json ./src/express.ts"
What's namespace?

2021-10-26 18:25 UTC, etiennenoel commented on src/express.ts
> +                    [`${AwsModuleKeyname}.region`]: await (new EnvironmentVariableResolver("REGION").resolve()),
Shouldn't this be resolved automatically?

2021-10-26 18:25 UTC, etiennenoel commented on src/identity-providers/app.identity-provider.ts
> +export class AppIdentityProvider implements IdentityProviderInterface {
Might be interesting to comment here the goal of this class (since I forgot myself haha)

2021-10-26 18:25 UTC, etiennenoel commented on src/lambda.ts
> +            [`${AwsModuleKeyname}.region`] : await (new EnvironmentVariableResolver("REGION").resolve()),
Same thing here.

2021-10-26 18:25 UTC, etiennenoel commented on src/main.ts
> +            [`${AwsModuleKeyname}.region`] : await (new EnvironmentVariableResolver("REGION").resolve()),
Same thing here.

2021-10-29 13:52 UTC, mathieugh commented on package.json
> +    "express": " REGION=us-east-1 NAMESPACE=app.ca ts-node --project tsconfig.cjs.json ./src/express.ts"
That's what I was saying it's the env variable for auth0. I stopped there but there are plenty more variables that should be there.

2021-10-29 13:53 UTC, mathieugh commented on src/express.ts
> +                    [`${AwsModuleKeyname}.region`]: await (new EnvironmentVariableResolver("REGION").resolve()),
Yes but I wanted an example of how to resolve an env variable

2021-11-02 14:30 UTC, etiennenoel approved these changes

2021-11-02 14:45 UTC, merged